"""added image to project

Revision ID: 59e619a63120
Revises: 
Create Date: 2025-09-07 13:27:59.324504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e619a63120'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('like_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dislike_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('dislike_count')
        batch_op.drop_column('like_count')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
