"""empty message

Revision ID: 7b9b62df402b
Revises: b3492948bda6
Create Date: 2025-09-07 16:59:12.390470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9b62df402b'
down_revision = 'b3492948bda6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
