"""empty message

Revision ID: b3492948bda6
Revises: e707647048ce
Create Date: 2025-09-07 16:00:29.195954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3492948bda6'
down_revision = 'e707647048ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.String(length=50), nullable=True))
        batch_op.drop_column('dislike_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dislike_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
