"""Add comments table for ideas

Revision ID: b5e99a64dfc7
Revises: 99b23bc54e76
Create Date: 2025-09-07 22:47:09.508826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5e99a64dfc7'
down_revision = '99b23bc54e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('user', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project'], ['projects.id'], name=op.f('comment_project_fkey')),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name=op.f('comment_user_fkey')),
    sa.PrimaryKeyConstraint('user', 'project', name=op.f('comment_pkey'))
    )
    op.drop_table('comments')
    # ### end Alembic commands ###
